services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "93953"
      POSTGRES_DB: "project"

  frontend:
    build: .
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:3000"
    depends_on:
      - postgres